# Generated by Django 4.2.4 on 2023-08-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='title',
            new_name='exhibit_title',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='archive',
            name='service_title',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='archive',
            name='team_member',
            field=models.CharField(default='팀원을 작성해주세요. (여러명일 경우 모두)', max_length=100),
        ),
        migrations.AlterField(
            model_name='archive',
            name='team_name',
            field=models.CharField(default='팀명을 작성해주세요.', max_length=30),
        ),
    ]
